services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: brasil_logistica_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis
      REVERB_HOST: reverb
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000

  reverb:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: brasil_logistica_reverb
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis
      REVERB_HOST: 0.0.0.0
    depends_on:
      - app
      - redis
    ports:
      - "8080:8080"
    command: php artisan reverb:start --host=0.0.0.0 --port=8080

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: brasil_logistica_queue
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis
      REVERB_HOST: reverb
    depends_on:
      - app
      - redis
    command: php artisan queue:listen --tries=1

  postgres:
    image: postgis/postgis:16-3.4
    container_name: brasil_logistica_postgres
    environment:
      POSTGRES_DB: brasil_logistica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: brasil_logistica_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

